#!/usr/bin/env bash

# Build and run the xframes docker container
mkdir -p notebooks
mkdir -p data

docker run -d --rm --name xframes \
    -p 8888:8888 -p 4040-4048:4040-4048 \
    -v $PWD/notebooks:/home/jovyan/work \
    -v $PWD/data:/data \
    xframes
